name: Bug Report
description: "Found a bug? Help us by reporting it, we'd love if you'd first take a look through our open issues, to make sure the issue isn't already filed."
body:
  - type: textarea
    id: "describe-the-bug"
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of what the bug is."
      placeholder: Tell us what you see.
    validations:
      required: true
  - type: textarea
    id: "to-reproduce"
    attributes:
      label: "To Reproduce"
      description: "Bug reports with clear reproduction will get prioritized higher and addressed more quickly."
      placeholder: "Steps to reproduce: 1. Go to '...' 2. Click on '...' 3. Scroll down to '...' 4. See error '...'"
    validations:
      required: true
  - type: textarea
    id: "expected-behaviour"
    attributes:
      label: "Expected behaviour"
      description: "A clear and concise description of what you expected to happen."
      placeholder: Tell us what you expect to see.
    validations:
      required: false
  - type: dropdown
    id: "blocker"
    attributes:
      label: "Does this block you from using Wip daily?"
      description: "All feedback will be reviewed, even if you select 'No'."
      multiple: false
      options:
        - "Yes"
        - "No"
    validations:
      required: true      
  - type: textarea
    id: "screenshots"
    attributes:
      label: "Screenshots"
      description: "If applicable, add screenshots to help explain your problem. While optional, screenshots can help expedite the time in which your bug is addressed."
    validations:
      required: false
  - type: dropdown
    id: "os"
    attributes:
      label: "Operating System"
      multiple: false
      options:
        - MacOS
        # - Windows
        # - Linux
    validations:
      required: false
  - type: input
    id: "os-version"
    attributes:
      label: "OS Version"
      description: "For example, `12.5`."
    validations:
      required: true
  - type: textarea
    id: "wip-version"
    attributes:
      label: "Wip Version"
      description: "Run `wip version` from your repo directory and paste the output here"
    validations:
      required: true
  - type: textarea
    id: "additional-context"
    attributes:
      label: "Additional context"
      description: "Add any other context about the problem here."
    validations:
      required: false

